package com.terminalvelocitycabbage.tvscript;

public enum TokenType {
    // Single-character tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, COLON, SEMICOLON, SLASH, STAR,
    PERCENT, PIPE, QUESTION, AT,

    // One or two character tokens
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    PLUS_PLUS, MINUS_MINUS,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, PERCENT_EQUAL,
    DOT_DOT, ARROW,

    // Literals
    IDENTIFIER, STRING, STRING_PART, INTEGER, DECIMAL,

    // Keywords
    IMPORT, MAIN, PUBLIC, PRIVATE, PROTECTED, MOD,
    VAR, CONST,
    TYPE_INTEGER, TYPE_DECIMAL, TYPE_STRING, TYPE_BOOLEAN,
    FUNCTION, RETURN, IF, ELSE, FOR, WHILE, MATCH, DEFAULT,
    BREAK, CONTINUE, PRINT, NONE, CLASS, NEW, TRAIT, TYPE,
    OPERATOR, THIS, SUPER, OVERRIDE, IS, HAS, AS,
    LIST, SET, MAP, ENUM, EVENT, ON, DISPATCH, ANNOTATION,
    THROW, THROWS, TRY, CATCH, ASYNC, AWAIT, LAUNCH, ALL, TIMEOUT, PASS,
    // Logical operators
    AND, OR, TRUE, FALSE,

    // Indentation and Newlines
    INDENT, DEDENT, NEWLINE,

    EOF
}
